FROM openjdk:17-slim
ARG DATABASE_URL
ARG USERNAME
ARG PASSWORD
ENV DATABASE_URL=$DATABASE_URL
ENV USERNAME=$USERNAME
ENV PASSWORD=$PASSWORD
COPY target/CineMatchBackend-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app.jar"]